version: '3.8'

services:
  ingressor:
    build: ..
    ports:
      - "8000:8000"
    volumes:
      # Mount your kubeconfig
      - ~/.kube:/root/.kube:ro
      # Mount configuration
      - ./sample-config.yaml:/app/config.yaml:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: ["ingressor", "serve", "--config", "/app/config.yaml", "--host", "0.0.0.0"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (if you want to add persistence later)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5 